// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "iris_sdk_flutter",
    platforms: [
        // Matches PassportReader.xcframework's own MinimumOSVersion.
        .iOS("16.0"),
    ],
    products: [
        .library(name: "iris-sdk-flutter", targets: ["iris_sdk_flutter"]),
    ],
    dependencies: [
        // Generated by the Flutter tool next to this package at build time.
        // Flutter 3.47 names it FlutterFramework; older SDKs generated a
        // package called Flutter instead, so this manifest requires 3.47+.
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        // The vendor SDK. A binary target's path must stay inside the package
        // directory, which is why the xcframework lives here rather than at
        // ios/ — the podspec reaches down into this directory for it.
        .binaryTarget(
            name: "PassportReader",
            path: "PassportReader.xcframework"
        ),
        .target(
            name: "iris_sdk_flutter",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "PassportReader",
            ]
        ),
    ]
)
